# Generated by Django 4.2.7 on 2025-10-28 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcription', models.TextField()),
                ('quality_rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('is_consensus', models.BooleanField(default=False)),
                ('similarity_scores', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'annotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'annotation_tasks',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsensusResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_transcription', models.TextField()),
                ('consensus_score', models.FloatField()),
                ('annotation_count', models.IntegerField()),
                ('similarity_matrix', models.JSONField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'consensus_results',
            },
        ),
    ]
