# Generated by Django 4.2.7 on 2025-10-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotations', '0001_initial'),
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consensusresult',
            name='clip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consensus_result', to='audio.audioclip'),
        ),
        migrations.AddField(
            model_name='consensusresult',
            name='contributing_annotations',
            field=models.ManyToManyField(related_name='consensus_results', to='annotations.annotation'),
        ),
    ]
