# Generated by Django 4.2.7 on 2025-10-28 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotationtask',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_tasks', to='audio.audioclip'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='audio.audioclip'),
        ),
        migrations.AddIndex(
            model_name='annotationtask',
            index=models.Index(fields=['status', 'priority'], name='annotation__status_eef7de_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationtask',
            index=models.Index(fields=['assigned_to', 'status'], name='annotation__assigne_0bd0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['clip', 'validated'], name='annotations_clip_id_5808b0_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['annotator', 'created_at'], name='annotations_annotat_9b04dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('clip', 'annotator')},
        ),
    ]
