# Generated by Django 4.2.7 on 2025-10-28 19:42

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('contributor', 'Contributor'), ('validator', 'Validator'), ('admin', 'Admin'), ('researcher', 'Researcher')], default='contributor', max_length=20)),
                ('wallet_address', models.CharField(blank=True, max_length=42, null=True, unique=True)),
                ('wallet_signature', models.TextField(blank=True, null=True)),
                ('wallet_verified', models.BooleanField(default=False)),
                ('balance_usdc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('total_contributions', models.IntegerField(default=0)),
                ('total_validations', models.IntegerField(default=0)),
                ('total_earnings_usdc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_contribution_date', models.DateField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('magic_link_token', models.CharField(blank=True, max_length=255, null=True)),
                ('magic_link_expires', models.DateTimeField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('badge_type', models.CharField(choices=[('first_contribution', 'First Contribution'), ('streak_7', '7 Day Streak'), ('streak_30', '30 Day Streak'), ('contributor_100', '100 Contributions'), ('validator_100', '100 Validations'), ('earnings_10', '$10 Earned'), ('earnings_100', '$100 Earned'), ('quality_expert', 'Quality Expert'), ('early_adopter', 'Early Adopter')], max_length=30, unique=True)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('points_reward', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'badges',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_badges',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['wallet_address'], name='users_wallet__54d389_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['firebase_uid'], name='users_firebas_361636_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
    ]
